name: Cypress Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome --config-file cypress.json --config video=false --env configFile=qa --group ${{ github.event.inputs.group }} --parallel true --ci-build-id ${{ github.run_id }} --spec /home/runner/work/testes-automatizados/testes-automatizados/cypress/e2e/AnalyticTestes/CadastrarProtocolo.js